config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/profile'
  get 'dashboard/super_secret'

  resources :login, only: [:new, :create]

  root "login#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device.rb
# This could be a factory to model against different device types. For now, keeping it simple.
class Device < ApplicationRecord
  belongs_to :user

  def approved?(client)
    return true if os_name.include?(client.os_name) && kind == client.device_type
    return false
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :devices

  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  # this could be abstracted out into a Service
  def check_device_policy(client)
    devices.any? { |device| device.approved?(client) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

    def current_user
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_user
  before_action :verify_device, only: [:super_secret]

  def index; end

  def profile; end

  def super_secret; end

  private

  def set_user
    @user = current_user
  end

  def verify_device
    client = DeviceDetector.new(request.user_agent)
    unless @user.check_device_policy(client)
      redirect_to dashboard_profile_path, notice: "🛑 Your device does not meet the requirements to access this resource!"
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new; end

  def create
    @user = User.find_by_email(params[:email])
    if @user.password == params[:password]
      session[:user_id] = @user.id
      redirect_to dashboard_index_path
    else
      redirect_to :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/dashboard/index.html.erb
<p>Welcome to your dashboard, <%= @user.full_name %>!</p>

app/views/dashboard/profile.html.erb
<h1>Profile</h1>
<p><strong>Name: </strong><%= @user.full_name %></p>
<p><strong>Email: </strong><%= @user.email %></p>
<p><strong>Location: </strong><%= @user.location %></p>

<h2>Registered devices</h2>
<% @user.devices.each do |device| %>
  <p><strong>Device: </strong><%= device.name %></p>
  <p><strong>Type: </strong><%= device.kind %></p>
<% end %>

app/views/dashboard/super_secret.html.erb
<h1>Super secret 🤫</h1>
<p>I am only viewable from approved device!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZtaPoc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>Employee Dashboard</h1>
    <% if flash[:notice]%>
      <p><%= flash[:notice] %></p>
    <% end %>

    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<h2>Log In</h2>

<%= form_with url: "/login", method: :post do |form| %>

  <%= form.label :email %>
  <%= form.text_field :email, placeholder: "steve@apple.com" %>
  <%= form.label :password %>
  <%= form.password_field :password, placeholder: "password" %>
  <br>
  <%= form.submit "Log me in, Scotty" %>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <%= link_to "Home", dashboard_index_path %>
  <%= link_to "Profile", dashboard_profile_path %>
  <%= link_to "Super Secret", dashboard_super_secret_path %>
</nav>